services:
  - type: web
    name: mi-app-django
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py migrate && gunicorn punto_venta.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: tu_proyecto.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mi-db
          property: connectionString

databases:
  - name: mi-db
    plan: free
    databaseName: mi_db
    user: mi_user
