services:
  - type: web
    name: mi-app-django
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn punto_venta.wsgi:application"
    preDeployCommand: "python manage.py migrate"  # 👈 ¡Este comando es clave!
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: punto_venta.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mi-db
          property: connectionString

databases:
  - name: mi-db
    plan: free
    databaseName: mi_db
    user: mi_user
