# Generated by Django 5.1.7 on 2025-05-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descuento',
            field=models.IntegerField(default=0),
        ),
    ]
