# Generated by Django 5.2.7 on 2025-11-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_mayoreo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='umbral_mayoreo',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='producto',
            name='no_folio',
            field=models.CharField(max_length=20),
        ),
    ]
