# Generated by Django 5.2.7 on 2025-12-02 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_precio_mayoreo_producto_umbral_mayoreo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'ADMINISTRADOR'), ('USUARIO', 'VENDEDOR'), ('CAJA', 'CAJA')], default='ADMIN', max_length=10),
        ),
    ]
