# Generated by Django 5.2.7 on 2025-12-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('pieza', 'PIEZA'), ('paquete', 'PAQUETE'), ('caja', 'CAJA'), ('granel', 'GRANEL')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
