# Generated by Django 5.2.7 on 2026-01-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_producto_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'ADMINISTRADOR'), ('CAJA', 'CAJA')], default='ADMIN', max_length=10),
        ),
    ]
