# Generated by Django 5.2.7 on 2026-02-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sucursal_remove_producto_stock_fisico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='sucursal',
        ),
        migrations.AddField(
            model_name='usuario',
            name='sucursales',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='core.sucursal'),
        ),
    ]
