# Generated by Django 5.2.7 on 2026-02-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_usuario_sucursal_alter_usuario_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='no_folio',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
