# Generated by Django 5.2.7 on 2026-02-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_categoria_prefijo_producto_referencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='prefijo',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='referencia',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
