# Generated by Django 5.2.7 on 2026-03-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_categoria_prefijo_alter_producto_referencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secuenciacategoria',
            options={'verbose_name': 'Secuencia de categoría'},
        ),
    ]
